kind: Service
apiVersion: v1
metadata:
  name: mongodb-sink-np
  namespace: mongo-sink
spec:
  type: NodePort
  selector:
    app: mongodb-sink-svc
  ports:
    - port: 27017
      nodePort: 30000

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb-source-np
  namespace: mongo-source
spec:
  type: NodePort
  selector:
    app: mongodb-source-svc
  ports:
    - port: 27017
      nodePort: 30001